application: quickseq0
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap
- url: /assets
  static_dir: assets
- url: /.*
  script: helloworld.app
  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest